### ISSUE TITLE
Bug creation RR

### ISSUE THREAD

**Issue by thebignaine** [motion-development/bugs#10]
Hello, 

When i had a RR with 7 roles. When i try to create a RR with 9 rôle i got this error message : 

Oh something went wrong. Please report this error to the bot owner.
ERROR ID: t2s5i8pfvk
ERROR Description: Command raised an exception: IndexError: list index out of range

Thanks for helping !

**Comment by TechnicPepijn** [comment]
Hey, can you send a screenshot where you ping the roles? Thanks

**Comment by thebignaine** [comment]
Sure : http://prntscr.com/139vcml

**Comment by TechnicPepijn** [comment]
Hey you will need to add a `-` between each role mention. Example:
`@Role - @Role - @Role`

Image example:
![img](https://cdn.motiondevelopment.top/u/other/A3Rf3LIP4riDKwzpsQ4nbAltEN5LoG.png)

**Comment by thebignaine** [comment]
I didn't use the "-" for last creation, i'll try :)

**Comment by thebignaine** [comment]
Perfect :)

**Comment by TechnicPepijn** [comment]
Glad it worked :)
