### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by acatiadroid** [motion-development/bugs#31]
Just some more typos/punctuation corrections on the site.

## Account Verification

![alt-text](https://cdn.discordapp.com/attachments/763535909433376788/850495661547061288/unknown.png)

## Profile settings - user-info

![alt-text](https://cdn.discordapp.com/attachments/763535909433376788/850497847068721152/unknown.png)

## Documentation - Bot Requirements
I just decided to completely rewrite the Bot Requirements documentation. There were quite a lot of errors found. Below I have corrected (hopefully) all of them.
 
> (1) User must be the owner
> The user who adds the bot to the site MUST be the owner of the bot. If the user is not the owner, we can ban the user from adding new bots. We can also ban the user from our site.
> 
> (2) Original bot
> The bot the user submits must be original and not some copy from another bot. The bot must be created by the user and not be a bot generator.
> 
> (3) No NSFW content
> The users' bot CANNOT have NSFW content within the bot's features or description. The bot is allowed to have NSFW content, but it must be locked to NSFW channels. The user may not show any of these commands in the description of the bot. The user also may not include any NSFW words in the description.
> 
> (4) Working bot
> The bot submitted by the user should be a working bot with errors if a user does something wrong. For example, when the bot requires to send embeds, there should be an error if the bot can't send embeds in the channel. If the bot does not give an error, it will NOT be accepted.
> 
> (5) Online Bot
> The bot must be online most of the time. Some downtime for maintenance is allowed. If the bot is offline too often, the bot will be removed from the site, and the bot must be online during verification.
> 
> (6) Public
> The bot must be public so people can invite it. Once the bot reaches 100 servers, the bot must be verified by Discord.
> (7) Support Server
> The bot must have a support server that can support everyone with issues about the bot. The server invite must be valid and working (Please don't use a vanity URL). Bot support servers must apply to Discord's TOS and guidelines.
> 
> (8) Discord TOS
> The bot must apply to Discords API TOS. Bots can't spam ban members in servers without reason, etc. If your bot does not comply with Discord's TOS, you will be banned from our site and reported to Discord.
> 
> That's all for now! Thanks for reading!

I only had time to do a few links on the site. I will create another issue if I identify more.

**Comment by TechnicPepijn** [comment]
Will be pushed at V1.2.1
