### ISSUE TITLE
"To many bots found for given data" when trying to visit my bots page

### ISSUE THREAD

**Issue by acatiadroid** [motion-development/bugs#4]
When visiting my bots page, https://www.motiondevelopment.top/bots/720785136425369652 it says:
```
BOT ERROR, contact site owner
Error Code: To many bots found for given data
REPORT ID: View_Bot-62
```

This seems to be a recurring issue.

**Comment by TechnicPepijn** [comment]
This issue occurs when your bot is found 2x in database. But I am not sure yet when it adds your bot a second time 🤔

**Comment by acatiadroid** [comment]
Yes very strange
