### ISSUE TITLE
Bot List Typos

### ISSUE THREAD

**Issue by acatiadroid** [motion-development/bugs#6]
I made this just to address all of the typos found on the Bot List.

Note that I have probably missed some and also I didn't count minor things such as missing full stops at the end of sentences.

### Edit user profile page

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837441085554556978/unknown.png)

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837442012566913064/unknown.png)

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837442324308688916/unknown.png)

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837442706702598174/unknown.png)

### Certification requirements documentation

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837443890134122506/unknown.png)

### Bot requirements

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837445908752236544/unknown.png)

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837446742050996224/unknown.png)

### API documentation

> Update bot status (POST)

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837447902833410068/unknown.png)

> Get Bot votes (GET) **AND** Get Bot info (GET) - they basically have the same typos.

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837448632822530098/unknown.png)

### Add bot

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837449477584584755/unknown.png)

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837450030184005662/unknown.png)

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837450538592370719/unknown.png)

### Home page

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837450819493560350/unknown.png)

### Find posts

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837451202332459028/unknown.png)

### Creating a post

![alt text](https://cdn.discordapp.com/attachments/763535909433376788/837452367518760970/unknown.png)

That's all I got, but I *may* likely missed some but I think I got most of the pages on the Bot list.

**Comment by TechnicPepijn** [comment]
Thanks for creating this issue. I have fixed all spelling errors you provided here. If you find more feel free to create a new issue.
