### ISSUE TITLE
Bot Bug Code lcijihr43b

### ISSUE THREAD

**Issue by Lemaan** [motion-development/bugs#7]
The Bot says: Command raised an exception: Forbidden: 403 Forbidden (error code: 50001): Missing Access. But I do all like everytime

**Comment by TechnicPepijn** [comment]
Forbidden means the bot can't do something. So does the bot have the following permissions?
* Send embedded links (If selected embed mode)
* Send messages in the selected channel
* Add reactions in the select channel
* Manage messages in the channel where you are setting up

If the bot has all those perms let me know and I will look into it!
