### ISSUE TITLE
There are 2 alti boxes

### ISSUE THREAD

**Issue by Falcn8** [motion-development/bugs#8]
![image](https://user-images.githubusercontent.com/63485306/119030001-34460300-b95e-11eb-9a51-4db151bacbf8.png)
This page is [my profile page](https://www.motiondevelopment.top/user/710698624891224135)

**Comment by TechnicPepijn** [comment]
Time to fix this error!

**Comment by TechnicPepijn** [comment]
Working on it rn!

**Comment by TechnicPepijn** [comment]
Finally! After some sweat this bug has been fixed!
